clc, clear
dataset = '2d';
%dataset = '20NewsGroup';
%dataset = 'Gisette';
%dataset = 'ECUESpam';
%dataset = 'URL-Reputation';
mat = [dataset,'_time.mat'];
load(mat);
figure; 
set(gcf,'Position',[100,100,1000,750], 'color','w');
LineWidth=3;
MarkerSize=8;
x=y(4:6,:);
t=1:6;
%x=x*4;
b=bar(x);
plot(t,x(1,:),'-ok','LineWidth',LineWidth,'MarkerSize',MarkerSize);
hold on;
plot(t,x(2,:),'--xb','LineWidth',LineWidth,'MarkerSize',MarkerSize);
hold on;
plot(t,x(3,:),'-vr','LineWidth',LineWidth,'MarkerSize',MarkerSize);
hold on;
xlabel('Number of Nodes Used','Fontsize',25,'fontweight','b');
ylabel('Running Time per Iteration/s','Fontsize',25,'fontweight','b');
set(gca,'fontsize',25,'fontweight','b');
legend('PSUBPLR-MR','PGDPLR-SPARK','PSUBPLR-SPARK');